// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: BTHome v2_xG24_xG27_sensors_with_LVGL

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
lv_obj_t * ui_BootScreen;
lv_obj_t * ui_imgsilabsbig;


// SCREEN: ui_ApplicationScreen
void ui_ApplicationScreen_screen_init(void);
lv_obj_t * ui_ApplicationScreen;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_imgbthome;
lv_obj_t * ui_imglvgl;
lv_obj_t * ui_imgsilabs;
lv_obj_t * ui_imgzephyr;
lv_obj_t * ui_labeltextSi7021;
lv_obj_t * ui_labelTempValue;
lv_obj_t * ui_labelcelciousSymbol;
lv_obj_t * ui_labelhumidityValue;
lv_obj_t * ui_labelhumiditypercent;
lv_obj_t * ui_labelVEML6035;
lv_obj_t * ui_labelSI7210Hall;
lv_obj_t * ui_labelBMP384Barometric;
lv_obj_t * ui_Bar2;
lv_obj_t * ui_labelICM20689;
lv_obj_t * ui_labelVEMLAmbientLightValue;
lv_obj_t * ui_labellxsymbol;
lv_obj_t * ui_labelsi7210HallEffectValue;
lv_obj_t * ui_labelmTSymbol;
lv_obj_t * ui_labelBMP384Value;
lv_obj_t * ui_labelmBarSymbol;
lv_obj_t * ui_labelOrientation;
lv_obj_t * ui_labelorientXvalue;
lv_obj_t * ui_Bar3;
lv_obj_t * ui_labelDegreesymbol1;
lv_obj_t * ui_labelorientYvalue;
lv_obj_t * ui_labelDegreesymbol2;
lv_obj_t * ui_labelorientZvalue;
lv_obj_t * ui_labelDegreesymbol3;
lv_obj_t * ui_labelAcceleration;
lv_obj_t * ui_labelg1Value;
lv_obj_t * ui_labelGSymbol1;
lv_obj_t * ui_labelg2Value;
lv_obj_t * ui_labelGSymbol2;
lv_obj_t * ui_labelg3Value;
lv_obj_t * ui_labelGSymbol3;
lv_obj_t * ui_labelxg24;
lv_obj_t * ui_Bar4;
lv_obj_t * ui_labelbroadcasted;
lv_obj_t * ui_labelsecond;
lv_obj_t * ui_labelsecago;


// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t * ui_SettingScreen;
lv_obj_t * ui_Bar5;
lv_obj_t * ui_imgBTHome;
lv_obj_t * ui_labelSetting;
void ui_event_btnback(lv_event_t * e);
lv_obj_t * ui_btnback;
lv_obj_t * ui_LabelBack;
lv_obj_t * ui_labelBoardcastenable;
lv_obj_t * ui_labelDeviceName;
lv_obj_t * ui_labelboardcastperiod;
lv_obj_t * ui_labelencryptkey;
void ui_event_swboardcastenable(lv_event_t * e);
lv_obj_t * ui_swboardcastenable;
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_txtdevicename;
lv_obj_t * ui_txtboardcastperiod;
lv_obj_t * ui_txtencryptkey;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[1] = {&ui_img_25_png};
const lv_img_dsc_t * ui_imgset_25_[1] = {&ui_img_25_78_png};
const lv_img_dsc_t * ui_imgset_30_[1] = {&ui_img_30_60_png};
const lv_img_dsc_t * ui_imgset_35_[1] = {&ui_img_35_67_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_imgbthome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    (void) target;
    if(event_code == LV_EVENT_PRESSED) {
        bthome_pressed_handle(e);
    }
}
void ui_event_btnback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    (void) target;
    if(event_code == LV_EVENT_PRESSED) {
        back_pressed_callback(e);
    }
}
void ui_event_swboardcastenable(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    (void) target;
    if(event_code == LV_EVENT_CLICKED) {
        swboardcast_enable_callback(e);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    (void) target;
    if(event_code == LV_EVENT_READY) {
        keyboard_ready_callback(e);
        _ui_state_modify(ui_txtdevicename, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_txtboardcastperiod, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_txtencryptkey, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_txtdevicename(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    (void) target;
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_txtdevicename);
    }
}
void ui_event_txtboardcastperiod(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    (void) target;
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_txtboardcastperiod);
    }
}
void ui_event_txtencryptkey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    (void) target;
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_txtencryptkey);
    }
}

///////////////////// SCREENS /////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_BootScreen_screen_init();
    ui_ApplicationScreen_screen_init();
    ui_SettingScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_BootScreen);
}
