// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: BTHome v2_xG24_xG27_sensors_with_LVGL

#ifndef _BTHOME_V2_XG24_XG27_SENSORS_WITH_LVGL_UI_H
#define _BTHOME_V2_XG24_XG27_SENSORS_WITH_LVGL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
extern lv_obj_t * ui_BootScreen;
extern lv_obj_t * ui_imgsilabsbig;
// CUSTOM VARIABLES

// SCREEN: ui_ApplicationScreen
void ui_ApplicationScreen_screen_init(void);
extern lv_obj_t * ui_ApplicationScreen;
extern lv_obj_t * ui_Bar1;
void ui_event_imgbthome(lv_event_t * e);
extern lv_obj_t * ui_imgbthome;
void ui_event_imglvgl(lv_event_t * e);
extern lv_obj_t * ui_imglvgl;
extern lv_obj_t * ui_imgsilabs;
extern lv_obj_t * ui_imgzephyr;
extern lv_obj_t * ui_labeltextSi7021;
extern lv_obj_t * ui_labelTempValue;
extern lv_obj_t * ui_labelcelciousSymbol;
extern lv_obj_t * ui_labelhumidityValue;
extern lv_obj_t * ui_labelhumiditypercent;
extern lv_obj_t * ui_labelVEML6035;
extern lv_obj_t * ui_labelSI7210Hall;
extern lv_obj_t * ui_labelBMP384Barometric;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_labelICM20689;
extern lv_obj_t * ui_labelVEMLAmbientLightValue;
extern lv_obj_t * ui_labellxsymbol;
extern lv_obj_t * ui_labelsi7210HallEffectValue;
extern lv_obj_t * ui_labelmTSymbol;
extern lv_obj_t * ui_labelBMP384Value;
extern lv_obj_t * ui_labelmBarSymbol;
extern lv_obj_t * ui_labelOrientation;
extern lv_obj_t * ui_labelorientXvalue;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_labelDegreesymbol1;
extern lv_obj_t * ui_labelorientYvalue;
extern lv_obj_t * ui_labelDegreesymbol2;
extern lv_obj_t * ui_labelorientZvalue;
extern lv_obj_t * ui_labelDegreesymbol3;
extern lv_obj_t * ui_labelAcceleration;
extern lv_obj_t * ui_labelg1Value;
extern lv_obj_t * ui_labelGSymbol1;
extern lv_obj_t * ui_labelg2Value;
extern lv_obj_t * ui_labelGSymbol2;
extern lv_obj_t * ui_labelg3Value;
extern lv_obj_t * ui_labelGSymbol3;
extern lv_obj_t * ui_labelxg24;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_labelbroadcasted;
extern lv_obj_t * ui_labelsecond;
extern lv_obj_t * ui_labelsecago;
// CUSTOM VARIABLES

// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
extern lv_obj_t * ui_SettingScreen;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_imgBTHome;
extern lv_obj_t * ui_labelSetting;
void ui_event_btnback(lv_event_t * e);
extern lv_obj_t * ui_btnback;
extern lv_obj_t * ui_LabelBack;
extern lv_obj_t * ui_labelBoardcastenable;
extern lv_obj_t * ui_labelDeviceName;
extern lv_obj_t * ui_labelboardcastperiod;
extern lv_obj_t * ui_labelencryptkey;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
void ui_event_txtdevicename(lv_event_t * e);
extern lv_obj_t * ui_txtdevicename;
void ui_event_txtboardcastperiod(lv_event_t * e);
extern lv_obj_t * ui_txtboardcastperiod;
void ui_event_txtencryptkey(lv_event_t * e);
extern lv_obj_t * ui_txtencryptkey;
void ui_event_swboardcastenable(lv_event_t * e);
extern lv_obj_t * ui_swboardcastenable;
// CUSTOM VARIABLES

// SCREEN: ui_TSCalibrationScreen
void ui_TSCalibrationScreen_screen_init(void);
extern lv_obj_t * ui_TSCalibrationScreen;
extern lv_obj_t * ui_Bar6;
extern lv_obj_t * ui_labelCalib;
void ui_event_btnback1(lv_event_t * e);
extern lv_obj_t * ui_btnback1;
extern lv_obj_t * ui_LabelBack1;
extern lv_obj_t * ui_labelValueX;
extern lv_obj_t * ui_labelValueY;
extern lv_obj_t * ui_imgLVGLlogo;
extern lv_obj_t * ui_labelPointX;
extern lv_obj_t * ui_labelPointY;
extern lv_obj_t * ui_labelValueXmin;
extern lv_obj_t * ui_labelValueYmin;
extern lv_obj_t * ui_labelValueXmax;
extern lv_obj_t * ui_labelValueYmax;
extern lv_obj_t * ui_labelValueRTouch;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TSCalibrationScreen;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1597985048);    // assets/silicon-labs-logo-red-2014-200px.png
LV_IMG_DECLARE(ui_img_25_png);    // assets/25.png
LV_IMG_DECLARE(ui_img_lvgl_logo_78_24_png);    // assets/lvgl_logo_78_24.png
LV_IMG_DECLARE(ui_img_30_60_png);    // assets/30_60.png
LV_IMG_DECLARE(ui_img_35_67_png);    // assets/35_67.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
